import type { EngineeringMilestone, FutureLessonModule } from './types'

export const futureLessonModules: FutureLessonModule[] = [
  {
    id: 'cpp-io-variables',
    domain: 'informatics-cpp',
    title: 'C++ 输入输出与变量',
    stage: 'L1',
    priority: 'high',
    status: 'planned',
    summary: '理解 cout、cin、变量和数据变化。',
    outcomes: ['会声明变量', '会读取输入', '会输出结果'],
    prerequisiteIds: [],
    pageKinds: ['intro', 'rule', 'animation', 'example', 'practice'],
    rewardFocus: ['star', 'badge'],
  },
  {
    id: 'cpp-condition',
    domain: 'informatics-cpp',
    title: 'C++ 判断语句 if',
    stage: 'L1',
    priority: 'high',
    status: 'planned',
    summary: '学会根据条件做不同选择。',
    outcomes: ['理解条件真假', '会写 if/else', '会解决简单比较问题'],
    prerequisiteIds: ['cpp-io-variables'],
    pageKinds: ['intro', 'rule', 'animation', 'example', 'practice'],
    rewardFocus: ['star', 'badge'],
  },
  {
    id: 'cpp-loop',
    domain: 'informatics-cpp',
    title: 'C++ 循环基础',
    stage: 'L1',
    priority: 'high',
    status: 'completed',
    summary: '理解 for 循环的执行顺序。',
    outcomes: ['会看循环变量', '会理解执行次数', '会做简单累加'],
    prerequisiteIds: ['cpp-io-variables'],
    pageKinds: ['intro', 'rule', 'animation', 'example', 'practice'],
    rewardFocus: ['star', 'badge'],
  },
  {
    id: 'cpp-array',
    domain: 'informatics-cpp',
    title: '数组与下标',
    stage: 'L1',
    priority: 'high',
    status: 'planned',
    summary: '理解数组像一排小抽屉，每个位置都有编号。',
    outcomes: ['认识数组', '理解下标', '会遍历数组'],
    prerequisiteIds: ['cpp-loop'],
    pageKinds: ['intro', 'rule', 'animation', 'example', 'practice'],
    rewardFocus: ['star', 'badge'],
  },
  {
    id: 'cpp-sort',
    domain: 'informatics-cpp',
    title: '排序算法启蒙',
    stage: 'L1',
    priority: 'high',
    status: 'completed',
    summary: '通过柱形图理解冒泡、选择、插入排序。',
    outcomes: ['会看比较与交换', '理解有序区', '会分析简单排序流程'],
    prerequisiteIds: ['cpp-array', 'cpp-loop'],
    pageKinds: ['intro', 'rule', 'animation', 'example', 'practice'],
    rewardFocus: ['star', 'badge', 'medal'],
  },
  {
    id: 'cpp-string',
    domain: 'informatics-cpp',
    title: '字符串与字符处理',
    stage: 'L2',
    priority: 'medium',
    status: 'planned',
    summary: '把单词和句子当作字符队伍来处理。',
    outcomes: ['认识字符与字符串', '会遍历字符串', '会做简单统计'],
    prerequisiteIds: ['cpp-array'],
    pageKinds: ['intro', 'rule', 'animation', 'example', 'practice'],
    rewardFocus: ['star', 'unlock'],
  },
  {
    id: 'cpp-function',
    domain: 'informatics-cpp',
    title: '函数与封装',
    stage: 'L2',
    priority: 'medium',
    status: 'planned',
    summary: '理解把重复工作装进函数里。',
    outcomes: ['会定义函数', '会传参数', '会返回结果'],
    prerequisiteIds: ['cpp-condition', 'cpp-loop'],
    pageKinds: ['intro', 'rule', 'animation', 'example', 'practice'],
    rewardFocus: ['badge', 'unlock'],
  },
  {
    id: 'cpp-enumeration',
    domain: 'informatics-cpp',
    title: '枚举与暴力搜索启蒙',
    stage: 'L2',
    priority: 'medium',
    status: 'planned',
    summary: '让程序一个个尝试所有可能。',
    outcomes: ['理解枚举', '会列举答案', '会缩小范围'],
    prerequisiteIds: ['cpp-loop', 'cpp-condition'],
    pageKinds: ['intro', 'rule', 'animation', 'example', 'practice', 'challenge'],
    rewardFocus: ['star', 'medal'],
  },
  {
    id: 'cpp-recursion',
    domain: 'informatics-cpp',
    title: '递归启蒙',
    stage: 'L3',
    priority: 'medium',
    status: 'planned',
    summary: '理解函数自己调用自己和问题拆小。',
    outcomes: ['认识递归', '会看递归树', '会解决简单递推'],
    prerequisiteIds: ['cpp-function'],
    pageKinds: ['intro', 'rule', 'animation', 'example', 'practice'],
    rewardFocus: ['badge', 'medal'],
  },
  {
    id: 'cpp-dfs-bfs',
    domain: 'informatics-cpp',
    title: '搜索算法基础',
    stage: 'L3',
    priority: 'medium',
    status: 'planned',
    summary: '理解深搜和广搜像走迷宫一样找答案。',
    outcomes: ['认识状态空间', '理解 DFS/BFS 差异', '会走简单迷宫'],
    prerequisiteIds: ['cpp-recursion', 'cpp-array'],
    pageKinds: ['intro', 'rule', 'animation', 'example', 'practice', 'challenge'],
    rewardFocus: ['medal', 'unlock'],
  },
  {
    id: 'math-counting',
    domain: 'math-olympiad',
    title: '加法原理与乘法原理',
    stage: 'L1',
    priority: 'high',
    status: 'planned',
    summary: '认识“分类加”和“分步乘”的计数思想。',
    outcomes: ['会分类计数', '会分步计数', '会画树状图'],
    prerequisiteIds: [],
    pageKinds: ['intro', 'rule', 'animation', 'example', 'practice'],
    rewardFocus: ['star', 'badge'],
  },
  {
    id: 'math-inclusion-exclusion',
    domain: 'math-olympiad',
    title: '容斥原理',
    stage: 'L1',
    priority: 'high',
    status: 'completed',
    summary: '理解重叠部分要减去再加回。',
    outcomes: ['会看韦恩图', '会列容斥式子', '会做交集题'],
    prerequisiteIds: ['math-counting'],
    pageKinds: ['intro', 'rule', 'animation', 'example', 'practice'],
    rewardFocus: ['star', 'badge'],
  },
  {
    id: 'math-shortest-path',
    domain: 'math-olympiad',
    title: '最短路线标数法',
    stage: 'L1',
    priority: 'high',
    status: 'completed',
    summary: '在格点图中用标数法数最短路线。',
    outcomes: ['会确定方向', '会看来源路径', '会解特殊形状'],
    prerequisiteIds: ['math-counting'],
    pageKinds: ['intro', 'rule', 'animation', 'example', 'practice'],
    rewardFocus: ['star', 'badge'],
  },
  {
    id: 'math-sports-tournament',
    domain: 'math-olympiad',
    title: '体育比赛中的学问',
    stage: 'L1',
    priority: 'high',
    status: 'completed',
    summary: '用动画理解淘汰赛、单循环赛、点线图和积分制。',
    outcomes: ['会求淘汰赛场数', '会求单循环赛场数', '会分析积分总分与平局'],
    prerequisiteIds: ['math-counting'],
    pageKinds: ['intro', 'rule', 'animation', 'example', 'practice'],
    rewardFocus: ['star', 'badge'],
  },
  {
    id: 'math-chicken-rabbit',
    domain: 'math-olympiad',
    title: '鸡兔同笼',
    stage: 'L1',
    priority: 'high',
    status: 'completed',
    summary: '用动画理解假设法、替换法和倒扣型题目。',
    outcomes: ['会抓住共同点与不同点', '会用假设法求数量', '会解决总只数未知型和倒扣型'],
    prerequisiteIds: ['math-counting'],
    pageKinds: ['intro', 'rule', 'animation', 'example', 'practice'],
    rewardFocus: ['star', 'badge'],
  },
  {
    id: 'math-find-pattern',
    domain: 'math-olympiad',
    title: '找规律',
    stage: 'L1',
    priority: 'high',
    status: 'planned',
    summary: '通过图形、数字和动作发现重复规律。',
    outcomes: ['会观察变化', '会预测下一项', '会总结规律'],
    prerequisiteIds: [],
    pageKinds: ['intro', 'rule', 'animation', 'example', 'practice'],
    rewardFocus: ['star', 'streak'],
  },
  {
    id: 'math-logic',
    domain: 'math-olympiad',
    title: '逻辑推理',
    stage: 'L1',
    priority: 'high',
    status: 'planned',
    summary: '通过排除法和条件表推理答案。',
    outcomes: ['会列表格', '会用排除法', '会梳理条件'],
    prerequisiteIds: [],
    pageKinds: ['intro', 'rule', 'animation', 'example', 'practice', 'challenge'],
    rewardFocus: ['badge', 'medal'],
  },
  {
    id: 'math-number-theory',
    domain: 'math-olympiad',
    title: '奇偶、倍数与余数',
    stage: 'L2',
    priority: 'high',
    status: 'planned',
    summary: '从数字性质入手解决巧算与判断题。',
    outcomes: ['理解奇偶性', '掌握整除与倍数', '会分析余数'],
    prerequisiteIds: ['math-find-pattern'],
    pageKinds: ['intro', 'rule', 'animation', 'example', 'practice'],
    rewardFocus: ['star', 'badge'],
  },
  {
    id: 'math-geometry',
    domain: 'math-olympiad',
    title: '平面几何与图形割补',
    stage: 'L2',
    priority: 'high',
    status: 'planned',
    summary: '用动画观察图形变化、拼接和转化。',
    outcomes: ['会割补图形', '会比较面积', '会观察角度关系'],
    prerequisiteIds: [],
    pageKinds: ['intro', 'rule', 'animation', 'example', 'practice', 'challenge'],
    rewardFocus: ['badge', 'medal'],
  },
  {
    id: 'math-application',
    domain: 'math-olympiad',
    title: '应用题模型',
    stage: 'L2',
    priority: 'high',
    status: 'planned',
    summary: '把鸡兔同笼、年龄、行程、工程等做成故事动画。',
    outcomes: ['会建模', '会画线段图', '会转成方程或列表'],
    prerequisiteIds: ['math-logic', 'math-number-theory'],
    pageKinds: ['intro', 'rule', 'animation', 'example', 'practice', 'challenge'],
    rewardFocus: ['star', 'badge', 'medal'],
  },
  {
    id: 'math-combinatorics',
    domain: 'math-olympiad',
    title: '排列组合启蒙',
    stage: 'L3',
    priority: 'medium',
    status: 'planned',
    summary: '通过排队、选卡片、走路线理解组合思想。',
    outcomes: ['会有序无序区分', '会做简单排列', '会做简单组合'],
    prerequisiteIds: ['math-counting'],
    pageKinds: ['intro', 'rule', 'animation', 'example', 'practice', 'challenge'],
    rewardFocus: ['medal', 'unlock'],
  },
]

export const engineeringMilestones: EngineeringMilestone[] = [
  {
    id: 'eng-module-registry',
    title: '建立模块注册表',
    priority: 'high',
    goal: '已统一首页导航、模块元信息和页面顺序，下一步继续把奖励与练习配置接入同一套注册协议。',
    deliverables: ['模块类型定义', 'src/course/registry.ts', '首页从 registry 渲染', 'AppShell 读取模块顺序'],
  },
  {
    id: 'eng-shared-lesson-components',
    title: '沉淀共享教学组件',
    priority: 'high',
    goal: '把代码演示、网格图、排序柱状图、题目反馈、奖励卡片做成可复用组件。',
    deliverables: ['LessonCode', 'GridDiagram', 'SortingBars', 'QuizCard', 'RewardPanel'],
  },
  {
    id: 'eng-content-data-layer',
    title: '建立内容数据层',
    priority: 'high',
    goal: '把文案、题目、案例、动画步骤定义从页面组件里抽离到 data 文件，便于多智能体协作。',
    deliverables: ['模块 meta 文件', 'practice 数据文件', 'example 数据文件', 'animation step schema'],
  },
  {
    id: 'eng-gamification-system',
    title: '加入游戏化激励系统',
    priority: 'high',
    goal: '让孩子在学习过程中获得星星、徽章、连续学习奖励和模块解锁反馈。',
    deliverables: ['学习积分模型', '完成记录存储', '徽章系统', '模块解锁逻辑'],
  },
  {
    id: 'eng-learning-profile',
    title: '建立学习档案与关卡地图',
    priority: 'medium',
    goal: '形成学习路径地图，让孩子看到自己学到哪里、下一站学什么。',
    deliverables: ['学习地图页', '主题分级', '通关状态', '推荐下一课'],
  },
  {
    id: 'eng-style-split',
    title: '拆分大体量样式与页面逻辑',
    priority: 'medium',
    goal: '已完成 AppShell 与首页重构，下一步继续把共享样式和模块样式彻底拆分，减小后续模块整合风险。',
    deliverables: ['src/modules 目录', '响应式 AppShell', '首页导航壳层', 'shared 样式继续拆分', '模块样式继续拆分'],
  },
]
